# Project
project.name = AuditManager

# browser defaults
browser=chrome
headless=false
env=qa


# selenium
retry.count=1
implicit.wait=10
explicit.wait=20
page.load.timeout=30

# reporting
screenshot.on.failure=true

# framework
base.path=/login

# extentreport

extentreport.title = Report | Automation Framework Selenium | Shriniwas
extentreport.name = ExtentReports
extentreport.folder = exports/ExtentReports
extentreport.attachment = exports/ExtentData
extentreport.override = no

# testdata - possible value can be either json or excel based on from where dataprovider should provide data from

testdata.source=excel

# Email Properties
email.enabled=true
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.username=shriniwas.automation@gmail.com
email.password=iarryknlyxdpptcf

email.to=turekar.shriniwas@gmail.com
email.cc=turekar.shriniwas@gmail.com
email.subject = Automation Execution Report
